name: myenv
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2020.11.06
  - xarray
  - hvplot
  - fsspec
  - s3fs
  - holoviews
  - cartopy
  - zarr
  - datashader
  - intake
  - intake-esm

